- hosts: localhost
  become: true
  tasks:
  - name: Install role dependencies
    local_action: command ansible-galaxy install -r requirements.yml
  - name: Install system utilities
    package:
      name: ['curl','wget','htop','ncdu','snapd','peek']
      state: present
  - name: Set up terminal
    include_role:
      name: gantsign.antigen
    vars:
      users:
        - username: jmenchero
          antigen_libraries:
            - name: oh-my-zsh
          antigen_theme:
            name: agnoster
          antigen_bundles:
            - name: git
            - name: pip
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting
            - name: zsh-autosuggestions
              url: zsh-users/zsh-autosuggestions
    # TODO: Add zshell aliases
  - name: Set up Windows Manager
    package:
      name: ['i3','i3lock']
      state: present
      # TODO: Add: xautolock, locker and user selection 
    # TODO: i3 config and keybindings
  - name: Install VSCode
    include_role:
      name: gantsign.visual-studio-code
    # TODO: VSCode config and extensions
  - name: Install Daily Use
    command: snap install {{item}} --classic
    with_items:
      - telegram-desktop
      - slack
      - spotify
      - chromium
  - name: Install Python packages
    package:
      name: ['python3','python3-dev','python3-pip','python','python-dev','python-pip','virtualenv']
      state: present
  - name: Install Python modules
    pip:
      name: ['psutil','memory-profiler']
      state: present
  - name: Install Node packages
    package:
      name: ['npm']
      state: present
  # - name: Install Node modules
  #   npm:
  #     name: ['nvm', '@vue/cli']
  #     global: yes
  #     state: present
  # - name: Install Docker
  #   include_role:
  #     name: nickjj.docker
  #   # TODO: Add Kubernetes
  # - name: Add fonts
  #   include_role:
  #     name: ontic.fonts
  #   vars:
  #     fonts_shared:
  #       - type: 'truetype'
  #         src: 'fonts/{{item}}.ttf'
  #         dest: 'mplus/{{item}}.ttf'
  #         with_items:
  #           - mplus-1m-thin
  #           - mplus-1m-light
  #           - mplus-1m-regular
  #           - mplus-1m-medium
  #           - mplus-1m-bold
  - name: Copy wallpaper
    copy:
      src: assets/wallpaper.jpg
      dest: /home/.wallpaper.jpg
  - name: Set GNOME wallpaper
    become_user: jmenchero
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///home/.wallpaper.jpg'"
  - name: Set GNOME lockscreen
    become_user: jmenchero
    dconf:
      key: "/org/gnome/desktop/screensaver/picture-uri"
      value: "'file:///home/.wallpaper.jpg'"
