- hosts: localhost
  become: true
  tasks:
  - name: Install role dependencies
    local_action: command ansible-galaxy install -r requirements.yml
  - name: Install system utilities
    package:
      name: ['curl','wget','htop','ncdu']
      state: present
  - name: Install terminal and windows managers
    package:
      name: ['terminator','zsh','i3','i3lock']
      state: present
  - name: Install VSCode
    include_role:
      name: gantsign.visual-studio-code
  - name: Install Oh My Zshell
    include_role:
      name: gantsign.antigen
    vars:
      users:
        - username: jmenchero
          antigen_libraries:
            - name: oh-my-zsh
          antigen_theme:
            name: agnoster
          antigen_bundles:
            - name: git
            - name: pip
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting
            - name: zsh-autosuggestions
              url: zsh-users/zsh-autosuggestions


# TODO: xautolock
# TODO:
# - name: Install VSCode
#   shell: |
#     wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
#     add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
#     apt install code
# - name: Install Docker
#   shell: |
#     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#     add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
#     apt update
#     sudo apt install docker-ce docker-ce-cli

# TODO: VSCode configurations
# TODO: Add fonts
# TODO: Deploy i3 and zsh configs
# TODO:
# - name: Install everyday use
#   apt: name={{item}}
#   with_items:
#     - chrome
#     - telegram
#     - spotify
# TODO:
# - name: Install programming utilities
#   apt: name={{item}}
#   with_items:
#     - node
#     - notepad
#     - npm
#     - pip
#     - postman
#     - python 
# TODO: Screenshot package