- hosts: localhost
  become: true
  tasks:
  - name: Install role dependencies
    local_action: command ansible-galaxy install -r requirements.yml
  - name: Install system utilities
    apt:
      name: ['curl','wget','htop','ncdu']
  - name: Install terminal and windows managers
    apt:
      name: ['terminator','zsh','i3','i3lock']
  # - name: Install Oh My Zsh with plug-ins
  #   shell: |
  #     sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  #     git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  #     git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting


# TODO: xautolock
# TODO:
# - name: Install VSCode
#   shell: |
#     wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
#     add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
#     apt install code
# - name: Install Docker
#   shell: |
#     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#     add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
#     apt update
#     sudo apt install docker-ce docker-ce-cli

# TODO: VSCode configurations
# TODO: Add fonts
# TODO: Deploy i3 and zsh configs
# TODO:
# - name: Install everyday use
#   apt: name={{item}}
#   with_items:
#     - chrome
#     - telegram
#     - spotify
# TODO:
# - name: Install programming utilities
#   apt: name={{item}}
#   with_items:
#     - node
#     - notepad
#     - npm
#     - pip
#     - postman
#     - python 
# TODO: Screenshot package